# Generated by Django 2.0.7 on 2018-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_phone_no', models.PositiveIntegerField()),
                ('user_email', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_conf_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
