# Generated by Django 2.0.7 on 2018-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
