# Generated by Django 2.0.7 on 2018-07-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlm', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
