# Generated by Django 2.0.7 on 2018-07-09 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlm', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docdate_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
